#ifndef ALL_COMMANDS_H
#define ALL_COMMANDS_H

#include "ls.h"
#include "cd.h"
#include "pwd.h"
#include "help.h"
#include "open.h"
#include "clear.h"
#include "mkdir.h"
#include "rmdir.h"
#include "rm.h"
#include "touch.h"
#include "echo.h"
#include "history.h"
#include "cat.h"
#include "cp.h"
#include "find.h"
#include "mv.h"
#include "ln.h"
#include "more.h"
#include "less.h"
#include "tail.h"
#include "head.h"
#include "ps.h"
#include "top.h"
#include "kill.h"
#include "killall.h"
#include "jobs.h"
#include "bg.h"
#include "fg.h"
#include "nohup.h"

#endif